GITHUB_URL = "https://api.github.com"
USERS = "/users"
REPOS = "/repos"
PRIVATE_REPO_READ_ACCESS_TOKEN = "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"
SLASH = "/"
COMMITS = "/commits"
USERNAME = "vaibhav-chauthe"